# Generated by Django 4.0 on 2022-03-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_rename_shipping_price_order_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postlCode',
            new_name='postalCode',
        ),
    ]
