# Generated by Django 4.0 on 2022-03-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isDeivered',
            new_name='isDelivered',
        ),
    ]
